ALTER TABLE "birth_profiles" DROP CONSTRAINT "birth_profiles_exact_time_check";--> statement-breakpoint
ALTER TABLE "chart_calculations" ADD COLUMN "input_snapshot_json" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "assets" ADD CONSTRAINT "assets_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_workspace_client_fk" FOREIGN KEY ("workspace_id","client_id") REFERENCES "public"."clients"("workspace_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_notes" ADD CONSTRAINT "client_notes_workspace_consultation_fk" FOREIGN KEY ("workspace_id","consultation_id") REFERENCES "public"."consultations"("workspace_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "consultations" ADD CONSTRAINT "consultations_workspace_chart_fk" FOREIGN KEY ("workspace_id","chart_id") REFERENCES "public"."chart_calculations"("workspace_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "generated_artifacts" ADD CONSTRAINT "generated_artifacts_workspace_chart_fk" FOREIGN KEY ("workspace_id","chart_id") REFERENCES "public"."chart_calculations"("workspace_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "generated_artifacts" ADD CONSTRAINT "generated_artifacts_workspace_consultation_fk" FOREIGN KEY ("workspace_id","consultation_id") REFERENCES "public"."consultations"("workspace_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "generated_artifacts" ADD CONSTRAINT "generated_artifacts_workspace_source_asset_fk" FOREIGN KEY ("workspace_id","source_asset_id") REFERENCES "public"."assets"("workspace_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "generated_artifacts" ADD CONSTRAINT "generated_artifacts_workspace_output_asset_fk" FOREIGN KEY ("workspace_id","output_asset_id") REFERENCES "public"."assets"("workspace_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "consent_records_one_active_purpose_unique" ON "consent_records" USING btree ("client_id","purpose") WHERE "consent_records"."revoked_at" is null;--> statement-breakpoint
ALTER TABLE "birth_profiles" ADD CONSTRAINT "birth_profiles_birth_date_check" CHECK ("birth_profiles"."birth_date" >= date '1900-01-01');--> statement-breakpoint
ALTER TABLE "birth_profiles" ADD CONSTRAINT "birth_profiles_exact_time_check" CHECK ("birth_profiles"."birth_time_accuracy" <> 'exact' or ("birth_profiles"."reported_birth_time" is not null and "birth_profiles"."reported_birth_time" = "birth_profiles"."calculation_birth_time" and "birth_profiles"."calculation_time_is_fallback" = false));--> statement-breakpoint
ALTER TABLE "clients" ADD CONSTRAINT "clients_preferred_contact_value_check" CHECK ("clients"."preferred_contact_method" is null or "clients"."preferred_contact_method" = 'none' or ("clients"."preferred_contact_method" = 'email' and "clients"."email" is not null) or ("clients"."preferred_contact_method" in ('phone', 'sms', 'whatsapp') and "clients"."phone_e164" is not null));