-- Email/password sign-in was never built: no form, no route, no code path
-- ever wrote a row here. Google is the only provider, and guest mode needs no
-- credential at all, so the table has been empty since migration 0004 created
-- it. lib/identity/password.ts, which produced the hash format this column
-- documented, is deleted in the same commit.
--
-- CASCADE is generated by drizzle-kit and is a no-op here: nothing references
-- auth_credentials. The foreign key runs the other way, to auth_users.
DROP TABLE "auth_credentials" CASCADE;
