/**
 * Rewrites the generated half of docs/what-the-readings-keep-hidden.md: how
 * many passages each book keeps hidden, by kind, and every one of them with
 * its recorded reason. The half above the markers is written by hand and is
 * left alone.
 *
 *   npm run knowledge:hidden-report             # rewrite the doc from the corpus files
 *   npm run knowledge:hidden-report -- --check  # fail if the doc is out of date
 *
 * Run it after any corpus build; the tests run it with --check.
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { knowledgeCorpusSchema, type KnowledgePassage } from "../../lib/knowledge/corpus";
import { KNOWLEDGE_SOURCES } from "../../lib/knowledge/sources";

const DOC = resolve("docs/what-the-readings-keep-hidden.md");
const CORPUS_DIR = resolve("lib/knowledge/corpus");
const START = "<!-- hidden-report:start (generated by npm run knowledge:hidden-report; do not edit by hand) -->";
const END = "<!-- hidden-report:end -->";

/** The kinds, in the order a passage is sorted into them: the first that matches its reason. */
export const KINDS: { kind: string; test: RegExp }[] = [
  { kind: "The malefic-yogas chapter, hidden whole", test: /chapter on malefic yogas/i },
  { kind: "Words the owner chose to keep hidden", test: /the owner keeps/i },
  { kind: "A sentence broken by a missing page", test: /missing page/i },
  { kind: "Eunuchs and hermaphrodites", test: /hermaphrodit|eunuch/i },
  {
    kind: "Death, widowhood and lifespan",
    test: /death|\bdie|dying|widow|lifespan|short life|kill|vishakanya|poisonous girl|loss of (children|sons|spouse)|danger to life/i,
  },
  {
    kind: "Caste and birth status",
    test: /caste|brahmin|low birth|low social|birth status|illegitim|her class|women under prohibition/i,
  },
  { kind: "Harm to a parent, partner or child", test: /harm to|harm or death/i },
  { kind: "Crime, violence and imprisonment", test: /crime|theft|thie|robber|violen|tortur|imprison|duel|fight|murder|trade in women/i },
  {
    kind: "Illness, injury, disability and deformity",
    test: /disease|ill(ness| health)|sick|injur|deform|disab|blind|defect|disfigur|madness|mental|menstrual|miscarriage|medical|physical|heartburn|phlegm|bilious|weakness|ailment/i,
  },
];
const OTHER = "Other";

export function kindOf(reason: string): string {
  return KINDS.find(({ test }) => test.test(reason))?.kind ?? OTHER;
}

type Hidden = KnowledgePassage & { category: string };

function hiddenPassages(): Hidden[] {
  return readdirSync(CORPUS_DIR)
    .filter((file) => file.endsWith(".json"))
    .sort()
    .flatMap((file) => knowledgeCorpusSchema.parse(JSON.parse(readFileSync(resolve(CORPUS_DIR, file), "utf8"))).passages)
    .filter((passage) => passage.withheld)
    .map((passage) => ({ ...passage, category: kindOf(passage.withheldReason ?? "") }));
}

const excerpt = (text: string) => {
  const flat = text.replace(/\s+/g, " ").trim();
  return flat.length > 110 ? `${flat.slice(0, 107).trimEnd()}...` : flat;
};

export function report(): string {
  const hidden = hiddenPassages();
  const books = [...new Set(hidden.map((passage) => passage.source))];
  const totals = new Map(
    books.map((book) => {
      const corpus = knowledgeCorpusSchema.parse(JSON.parse(readFileSync(resolve(CORPUS_DIR, `${book}.json`), "utf8")));
      return [book, corpus.passages.length];
    }),
  );
  const kinds = [...KINDS.map(({ kind }) => kind), OTHER].filter((kind) => hidden.some((passage) => passage.category === kind));
  const title = (book: string) => KNOWLEDGE_SOURCES[book]?.shortTitle ?? book;
  const count = (kind: string, book: string) => hidden.filter((p) => p.category === kind && p.source === book).length;

  const lines: string[] = [];
  lines.push("## How many, by kind", "");
  lines.push(`| Kind | ${books.map(title).join(" | ")} |`);
  lines.push(`| --- | ${books.map(() => "---:").join(" | ")} |`);
  for (const kind of kinds) lines.push(`| ${kind} | ${books.map((book) => count(kind, book)).join(" | ")} |`);
  lines.push(
    `| **Hidden in all** | ${books.map((book) => `**${hidden.filter((p) => p.source === book).length}** of ${totals.get(book)}`).join(" | ")} |`,
  );
  lines.push("");
  lines.push("A passage is counted under the first kind its recorded reason names, in the order above.", "");
  lines.push("## Every hidden passage", "");
  lines.push("Grouped by kind, then by book and place in the book. Each line gives the passage's id, the reason recorded for it, and how it begins.", "");
  for (const kind of kinds) {
    const own = hidden.filter((passage) => passage.category === kind);
    lines.push(`### ${kind} (${own.length})`, "");
    for (const passage of own) {
      lines.push(`- \`${passage.id}\`: ${passage.withheldReason} -- "${excerpt(passage.printedText ?? passage.text)}"`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

function main() {
  const doc = readFileSync(DOC, "utf8");
  const eol = doc.includes("\r\n") ? "\r\n" : "\n";
  const text = doc.replace(/\r\n/g, "\n");
  const start = text.indexOf(START);
  const end = text.indexOf(END);
  if (start < 0 || end < start) throw new Error(`${DOC} has no generated section between its markers.`);
  const next = `${text.slice(0, start + START.length)}\n\n${report()}\n${text.slice(end)}`;
  if (process.argv.includes("--check")) {
    if (next !== text) {
      console.error("docs/what-the-readings-keep-hidden.md is out of date: run `npm run knowledge:hidden-report`.");
      process.exitCode = 1;
    }
    return;
  }
  writeFileSync(DOC, next.replace(/\n/g, eol));
  console.log(`wrote the generated section of ${DOC}`);
}

if (process.argv[1]?.endsWith("hidden-report.ts")) main();
