/**
 * Deterministic Vedic Astrology Interpretations for Planetary Placements.
 * Based on classical Parashari and Jaimini principles.
 */

/* ── Planet in Sign (Rashi) ── */

export const PLANET_IN_SIGN: Record<string, Record<string, string>> = {
  Sun: {
    Aries: "Sun is exalted in Aries, granting powerful self-confidence, leadership drive, and a pioneering spirit. The native commands authority naturally and thrives in independent roles.",
    Taurus: "Sun in Taurus produces a steady, determined personality focused on material security and sensory comfort. There is artistic appreciation and a strong attachment to values.",
    Gemini: "Sun in Gemini creates a versatile intellect drawn to communication, writing, and learning. The native is curious, adaptable, and socially engaged with dual interests.",
    Cancer: "Sun in Cancer deepens emotional sensitivity and connection to home and family. The native draws strength from nurturing others and may excel in public-facing roles.",
    Leo: "Sun in its own sign Leo radiates confidence, creativity, and natural authority. There is a strong desire for recognition, dramatic self-expression, and generous leadership.",
    Virgo: "Sun in Virgo channels vitality into service, analysis, and perfectionism. The native excels in detail-oriented work, health matters, and practical problem-solving.",
    Libra: "Sun is debilitated in Libra, creating tension between self-assertion and the need for harmony. Partnerships and diplomacy are central life themes requiring conscious balance.",
    Scorpio: "Sun in Scorpio produces intense willpower, investigative depth, and transformative energy. The native is drawn to mysteries, psychology, and wielding hidden power.",
    Sagittarius: "Sun in Sagittarius inspires philosophical vision, optimism, and a quest for higher truth. The native is drawn to travel, teaching, and expanding their worldview.",
    Capricorn: "Sun in Capricorn drives ambitious, disciplined pursuit of long-term goals. The native values structure, responsibility, and earns authority through persistent effort.",
    Aquarius: "Sun in Aquarius creates a humanitarian, unconventional personality with strong ideals. The native thinks independently and is drawn to social reform and innovation.",
    Pisces: "Sun in Pisces softens ego boundaries, enhancing compassion, imagination, and spiritual sensitivity. The native finds purpose through creative or healing pursuits.",
  },
  Moon: {
    Aries: "Moon in Aries creates emotionally impulsive, courageous responses. The native needs independence and action to feel emotionally secure, with quick but short-lived moods.",
    Taurus: "Moon is exalted in Taurus, granting deep emotional stability, sensory comfort, and a nurturing nature. The native finds peace through beauty, food, and material security.",
    Gemini: "Moon in Gemini produces a restless, curious mind that processes emotions through communication and intellectual analysis. Emotional needs shift frequently.",
    Cancer: "Moon in its own sign Cancer heightens intuition, emotional depth, and maternal instinct. The native is deeply connected to home, memory, and nurturing relationships.",
    Leo: "Moon in Leo creates a warm, dramatic emotional nature that craves recognition and creative expression. The native has generous affections and needs to feel special.",
    Virgo: "Moon in Virgo channels emotions into practical service and analytical thinking. The native processes feelings through routine, health consciousness, and helping others.",
    Libra: "Moon in Libra creates a refined emotional nature that seeks harmony, beauty, and balanced relationships. The native is diplomatic but may avoid emotional confrontation.",
    Scorpio: "Moon in Scorpio produces intense, transformative emotional experiences. The native has powerful intuition, deep attachments, and a need for emotional truth at all costs.",
    Sagittarius: "Moon in Sagittarius creates an optimistic, freedom-loving emotional nature. The native finds emotional fulfillment through travel, philosophy, and expansive experiences.",
    Capricorn: "Moon in Capricorn produces controlled, disciplined emotional responses. The native may appear reserved but has deep emotional endurance and practical nurturing instincts.",
    Aquarius: "Moon in Aquarius creates a detached, humanitarian emotional style. The native processes feelings intellectually and finds comfort in friendship and social ideals.",
    Pisces: "Moon in Pisces heightens emotional sensitivity, psychic receptivity, and compassion. The native absorbs others' feelings and needs creative or spiritual outlets for balance.",
  },
  Mars: {
    Aries: "Mars in its own sign Aries is at peak strength — bold, competitive, and action-oriented. The native is a natural warrior with strong initiative and physical vitality.",
    Taurus: "Mars in Taurus channels drive into material acquisition and steady determination. Actions are deliberate rather than impulsive, with strong sensual energy.",
    Gemini: "Mars in Gemini directs energy into communication, debate, and intellectual pursuits. The native is a sharp arguer but may scatter energy across too many interests.",
    Cancer: "Mars is debilitated in Cancer, creating emotional volatility and passive-aggressive tendencies. Energy is tied to home and family matters, requiring conscious channeling.",
    Leo: "Mars in Leo produces courageous, dramatic action with a flair for leadership. The native fights for pride and creative expression with generous but commanding energy.",
    Virgo: "Mars in Virgo channels energy into precise, methodical action. The native excels in technical work, health disciplines, and solving problems through detailed analysis.",
    Libra: "Mars in Libra directs energy toward partnerships and justice. The native acts through diplomacy and negotiation but may struggle with indecisiveness in conflict.",
    Scorpio: "Mars in its own sign Scorpio is intensely powerful — strategic, penetrating, and relentless. The native has extraordinary willpower and capacity for transformation.",
    Sagittarius: "Mars in Sagittarius channels energy into philosophical pursuits, adventure, and righteous causes. The native fights for beliefs and explores with physical boldness.",
    Capricorn: "Mars is exalted in Capricorn, producing disciplined, strategic action toward ambitious goals. The native builds lasting structures through persistent, calculated effort.",
    Aquarius: "Mars in Aquarius directs energy toward humanitarian causes and unconventional methods. The native fights for ideals and innovates through rebellious, progressive action.",
    Pisces: "Mars in Pisces channels energy into spiritual, creative, and compassionate action. The native may struggle with motivation clarity but excels in selfless service.",
  },
  Mercury: {
    Aries: "Mercury in Aries produces quick, decisive thinking with sharp but impatient communication. The native speaks directly, thinks fast, and excels in debates.",
    Taurus: "Mercury in Taurus creates methodical, practical thinking grounded in sensory reality. The native communicates deliberately and has a talent for financial analysis.",
    Gemini: "Mercury in its own sign Gemini is at peak intellectual agility — versatile, curious, and brilliantly communicative. The native excels in writing, teaching, and commerce.",
    Cancer: "Mercury in Cancer blends thought with emotion, creating intuitive intelligence and memory-based learning. Communication is nurturing but sometimes subjective.",
    Leo: "Mercury in Leo produces confident, dramatic communication with authoritative flair. The native thinks creatively and presents ideas with commanding presence.",
    Virgo: "Mercury is exalted in Virgo, producing the sharpest analytical mind — detail-oriented, discriminating, and exceptionally organized. The native excels in all intellectual work.",
    Libra: "Mercury in Libra creates balanced, diplomatic thinking focused on fairness and aesthetics. The native communicates gracefully and mediates with intellectual skill.",
    Scorpio: "Mercury in Scorpio produces penetrating, investigative thinking. The native uncovers hidden truths, thinks strategically, and communicates with transformative intensity.",
    Sagittarius: "Mercury in Sagittarius broadens thinking toward philosophy and big-picture vision. The native communicates with optimism but may overlook details for the larger truth.",
    Capricorn: "Mercury in Capricorn creates structured, pragmatic thinking oriented toward career goals. Communication is authoritative, concise, and business-minded.",
    Aquarius: "Mercury in Aquarius produces innovative, independent thinking with humanitarian scope. The native excels in technology, social theory, and unconventional ideas.",
    Pisces: "Mercury is debilitated in Pisces, blending logic with imagination and intuition. The native thinks poetically and may struggle with practical details but excels in creative fields.",
  },
  Jupiter: {
    Aries: "Jupiter in Aries expands through bold initiative, leadership, and pioneering ventures. The native grows through independent action and inspires others with enthusiasm.",
    Taurus: "Jupiter in Taurus expands through material abundance, sensory wisdom, and financial growth. The native attracts wealth and finds spiritual meaning in earthly pleasures.",
    Gemini: "Jupiter in Gemini expands through knowledge, communication, and diverse learning. The native teaches, writes, and grows through intellectual exploration.",
    Cancer: "Jupiter is exalted in Cancer, creating the most benevolent, nurturing wisdom. The native is blessed in home life, emotional intelligence, and maternal grace.",
    Leo: "Jupiter in Leo expands through creative self-expression, leadership, and generous authority. The native inspires others and attracts recognition through noble pursuits.",
    Virgo: "Jupiter in Virgo grows through service, health knowledge, and practical wisdom. The native teaches through detailed analysis and finds meaning in everyday duties.",
    Libra: "Jupiter in Libra expands through partnerships, justice, and aesthetic appreciation. The native grows through balanced relationships and diplomatic wisdom.",
    Scorpio: "Jupiter in Scorpio expands through deep transformation, occult knowledge, and psychological insight. The native gains wisdom through crisis and hidden truths.",
    Sagittarius: "Jupiter in its own sign Sagittarius is maximally expansive — philosophical, fortunate, and spiritually inclined. The native is a natural teacher and seeker of truth.",
    Capricorn: "Jupiter is debilitated in Capricorn, where expansion meets restriction. Growth comes slowly through discipline, career focus, and practical accomplishment.",
    Aquarius: "Jupiter in Aquarius expands through humanitarian ideals, innovation, and social networks. The native grows by serving collective causes and embracing progress.",
    Pisces: "Jupiter in its own sign Pisces reaches peak spiritual expression — compassionate, wise, and transcendent. The native embodies universal love and mystical understanding.",
  },
  Venus: {
    Aries: "Venus in Aries creates passionate, impulsive love and bold artistic expression. The native pursues beauty and pleasure with fiery enthusiasm and direct charm.",
    Taurus: "Venus in its own sign Taurus embodies pure sensual enjoyment — love of luxury, beauty, food, and comfort. Relationships are loyal, stable, and deeply pleasurable.",
    Gemini: "Venus in Gemini creates intellectual charm, witty flirtation, and diverse aesthetic interests. The native loves through communication and mental stimulation.",
    Cancer: "Venus in Cancer creates nurturing, emotionally devoted love. The native expresses affection through care, home-making, and deep sentimental attachment.",
    Leo: "Venus in Leo produces dramatic, generous, and royal expressions of love. The native creates beauty with flair and demands loyalty and admiration in return.",
    Virgo: "Venus is debilitated in Virgo, where love becomes analytical and service-oriented. The native shows affection through practical help but may be overly critical in relationships.",
    Libra: "Venus in its own sign Libra is the consummate romantic — harmonious, beautiful, and partnership-oriented. The native has refined taste and natural grace in all relationships.",
    Scorpio: "Venus in Scorpio creates intense, all-or-nothing love with deep emotional and sexual magnetism. The native transforms through passionate, sometimes obsessive attachments.",
    Sagittarius: "Venus in Sagittarius loves through adventure, freedom, and philosophical connection. The native is attracted to foreign cultures and expansive, optimistic partners.",
    Capricorn: "Venus in Capricorn expresses love through commitment, responsibility, and building lasting structures. Romance is practical, loyal, and matures beautifully over time.",
    Aquarius: "Venus in Aquarius creates unconventional, freedom-loving relationships with humanitarian aesthetics. The native values friendship in love and intellectual connection.",
    Pisces: "Venus is exalted in Pisces, creating the most transcendent, selfless love. The native has extraordinary artistic sensitivity and experiences love as a spiritual force.",
  },
  Saturn: {
    Aries: "Saturn is debilitated in Aries, where discipline clashes with impulsiveness. The native learns patience through frustrating delays in self-initiated projects.",
    Taurus: "Saturn in Taurus builds lasting material security through patient effort. The native develops strong financial discipline and enduring practical values.",
    Gemini: "Saturn in Gemini structures the intellect, creating serious, methodical communication. The native may be a slow but thorough learner who becomes an authority over time.",
    Cancer: "Saturn in Cancer restricts emotional expression, creating a reserved, duty-bound emotional nature. The native learns emotional maturity through family responsibilities.",
    Leo: "Saturn in Leo constrains creative self-expression and ego. The native earns authority gradually and learns to lead through humility rather than dramatics.",
    Virgo: "Saturn in Virgo excels in structured service, health discipline, and analytical rigor. The native builds expertise through meticulous, sustained practice.",
    Libra: "Saturn is exalted in Libra, producing masterful diplomacy, just authority, and balanced discipline. The native creates enduring partnerships and social structures.",
    Scorpio: "Saturn in Scorpio demands confrontation with deep fears and transformation. The native gains power through endurance in crisis and mastering hidden knowledge.",
    Sagittarius: "Saturn in Sagittarius structures philosophical beliefs and spiritual practice. The native becomes a disciplined teacher after testing their own convictions.",
    Capricorn: "Saturn in its own sign Capricorn is maximally powerful — ambitious, disciplined, and authoritative. The native builds lasting institutions through relentless effort.",
    Aquarius: "Saturn in its own sign Aquarius channels discipline into humanitarian structures and social reform. The native creates lasting systems that serve collective progress.",
    Pisces: "Saturn in Pisces structures spiritual growth and creative discipline. The native learns to ground imagination in practical form and serve through compassionate boundaries.",
  },
  Rahu: {
    Aries: "Rahu in Aries amplifies ambition, aggression, and desire for independent identity. The native obsessively pursues self-discovery and may take bold, unconventional paths.",
    Taurus: "Rahu in Taurus creates intense material desire, attachment to luxury, and unconventional financial strategies. The native is driven to accumulate wealth and sensory experiences.",
    Gemini: "Rahu in Gemini amplifies intellectual hunger, creating a brilliant but restless communicator. The native may excel in media, technology, or boundary-pushing ideas.",
    Cancer: "Rahu in Cancer intensifies emotional needs and attachment to homeland or family. The native seeks security through unconventional domestic arrangements.",
    Leo: "Rahu in Leo amplifies desire for fame, power, and dramatic self-expression. The native is drawn to spotlight roles and may achieve sudden recognition.",
    Virgo: "Rahu in Virgo drives obsessive perfectionism, health anxiety, and analytical intensity. The native may excel in alternative healing or technical innovation.",
    Libra: "Rahu in Libra amplifies desire for partnerships, luxury, and social status. The native is drawn to influential relationships and diplomatic manipulation.",
    Scorpio: "Rahu in Scorpio intensifies transformation obsession, occult fascination, and power dynamics. The native may experience dramatic upheavals that catalyze deep growth.",
    Sagittarius: "Rahu in Sagittarius amplifies philosophical seeking and desire for spiritual authority. The native may follow unconventional spiritual paths or foreign philosophies.",
    Capricorn: "Rahu in Capricorn drives relentless career ambition and desire for worldly status. The native achieves through unconventional professional strategies.",
    Aquarius: "Rahu in Aquarius amplifies humanitarian ideals and technological innovation. The native is drawn to social reform through avant-garde or disruptive methods.",
    Pisces: "Rahu in Pisces intensifies spiritual longing and escapist tendencies. The native may have vivid psychic experiences and is drawn to mystical or illusory realms.",
  },
  Ketu: {
    Aries: "Ketu in Aries indicates past-life mastery of independence and combat. The native has innate courage but is learning to detach from ego-driven aggression.",
    Taurus: "Ketu in Taurus signals past-life attachment to material comfort. The native has natural financial instincts but is learning to find value beyond possessions.",
    Gemini: "Ketu in Gemini indicates past-life intellectual development. The native has innate communication skills but is drawn toward intuitive knowing over analytical thinking.",
    Cancer: "Ketu in Cancer signals past-life emotional depth and family bonds. The native has strong nurturing instincts but is learning emotional independence.",
    Leo: "Ketu in Leo indicates past-life leadership and creative expression. The native has natural authority but is learning humility and detachment from personal glory.",
    Virgo: "Ketu in Virgo signals past-life service and analytical mastery. The native has innate precision but is learning to trust intuition over critical analysis.",
    Libra: "Ketu in Libra indicates past-life relationship mastery and diplomacy. The native has natural social grace but is learning to assert individual identity.",
    Scorpio: "Ketu in Scorpio signals past-life transformation and occult knowledge. The native has deep intuitive power and is learning to release controlling tendencies.",
    Sagittarius: "Ketu in Sagittarius indicates past-life philosophical or religious mastery. The native has innate wisdom but is learning to ground beliefs in practical reality.",
    Capricorn: "Ketu in Capricorn signals past-life authority and structural achievement. The native has natural discipline but is learning to value emotional over material success.",
    Aquarius: "Ketu in Aquarius indicates past-life humanitarian service and innovation. The native has progressive instincts but is learning personal emotional connection.",
    Pisces: "Ketu in Pisces signals past-life spiritual attainment and transcendence. The native has deep mystical sensitivity and may feel this world is not truly home.",
  },
};

/* ── Planet in House ── */

export const PLANET_IN_HOUSE: Record<string, Record<number, string>> = {
  Sun: {
    1: "Sun in the 1st house gives a strong personality, natural authority, and robust vitality. You lead from the front and your identity is central to your life path.",
    2: "Sun in the 2nd house focuses on wealth accumulation, family lineage, and powerful speech. Financial security and personal values are tied to self-worth.",
    3: "Sun in the 3rd house drives courage, self-expression, and sibling relationships. You communicate with authority and take bold initiatives.",
    4: "Sun in the 4th house connects identity to home, mother, and inner emotional life. Real estate, vehicles, and domestic happiness are important themes.",
    5: "Sun in the 5th house enhances creativity, romance, and connection with children. You shine through artistic expression and speculative intelligence.",
    6: "Sun in the 6th house gives strength over enemies, health consciousness, and service orientation. You excel in competitive environments and healing professions.",
    7: "Sun in the 7th house projects identity through partnerships and public dealings. Marriage and business partnerships are central to your life expression.",
    8: "Sun in the 8th house illuminates transformation, hidden knowledge, and inheritance. You may experience ego death and rebirth that strengthens your core identity.",
    9: "Sun in the 9th house connects identity to dharma, higher learning, and spiritual authority. You are naturally drawn to teaching, philosophy, and long-distance journeys.",
    10: "Sun in the 10th house is powerfully placed for career prominence and public reputation. You are destined for leadership and recognition in your professional field.",
    11: "Sun in the 11th house connects identity to social networks, gains, and fulfilled aspirations. Influential friendships and community leadership define your path.",
    12: "Sun in the 12th house turns identity inward toward spirituality, foreign lands, and liberation. You may find purpose through solitude, meditation, or overseas connections.",
  },
  Moon: {
    1: "Moon in the 1st house creates a sensitive, emotionally expressive personality. Your moods are visible and you connect with others through empathy and nurturing.",
    2: "Moon in the 2nd house ties emotional security to family wealth and nourishment. You have a soothing voice and find comfort in financial stability.",
    3: "Moon in the 3rd house creates emotional courage and communicative sensitivity. Short travels and sibling bonds are emotionally significant.",
    4: "Moon in the 4th house is powerfully placed for domestic happiness. You are deeply connected to mother, home, and inner emotional peace.",
    5: "Moon in the 5th house enhances creative imagination, romantic sensitivity, and connection with children. Your emotions fuel artistic expression.",
    6: "Moon in the 6th house channels emotions into service and health awareness. Emotional fluctuations may affect digestion and daily routines.",
    7: "Moon in the 7th house creates deep emotional needs in partnerships. Marriage brings emotional fulfillment and public appeal.",
    8: "Moon in the 8th house deepens emotional intensity and psychic sensitivity. Transformation comes through emotional crises that ultimately heal.",
    9: "Moon in the 9th house creates emotional connection to spiritual beliefs and long-distance travel. Mother may be philosophical or from a different culture.",
    10: "Moon in the 10th house brings public recognition and career success through emotional connection with the masses. Your professional image is caring and nurturing.",
    11: "Moon in the 11th house ties emotional fulfillment to friendships and social causes. You gain through nurturing your network and community.",
    12: "Moon in the 12th house creates deep emotional introspection and spiritual sensitivity. You find peace in solitude, meditation, and compassionate service.",
  },
  Mars: {
    1: "Mars in the 1st house creates a dynamic, competitive, physically strong personality. You act decisively and are naturally athletic and assertive.",
    2: "Mars in the 2nd house drives aggressive wealth pursuit and bold speech. You may earn through technical skills, property, or competitive fields.",
    3: "Mars in the 3rd house gives exceptional courage, physical initiative, and competitive drive among siblings. You excel in sports, writing, and bold ventures.",
    4: "Mars in the 4th house brings energy to property matters, vehicles, and home improvements. There may be turbulence in domestic life requiring conscious management.",
    5: "Mars in the 5th house creates passionate romance, competitive children, and bold creative expression. You take risks in speculation and love.",
    6: "Mars in the 6th house is excellently placed for defeating enemies, overcoming disease, and competitive success. You thrive in challenging environments.",
    7: "Mars in the 7th house brings passion and assertiveness to partnerships. Marriage may be fiery and dynamic, requiring balance between independence and compromise.",
    8: "Mars in the 8th house gives strength in crisis, surgical ability, and transformative power. You face life's dangers with courage and may have research talent.",
    9: "Mars in the 9th house channels energy into dharmic pursuits, higher learning, and righteous action. You may fight for beliefs and explore through adventure.",
    10: "Mars in the 10th house is powerfully placed for career achievement through assertive action. You excel in engineering, military, sports, or leadership roles.",
    11: "Mars in the 11th house drives energetic pursuit of gains and ambitious social networking. Elder siblings may be influential, and you achieve goals through bold action.",
    12: "Mars in the 12th house channels energy into spiritual practice, foreign lands, or institutional work. Hidden strength emerges through solitude and inner discipline.",
  },
  Mercury: {
    1: "Mercury in the 1st house creates an intelligent, communicative, youthful personality. You process the world through intellect and adapt quickly to any situation.",
    2: "Mercury in the 2nd house enhances articulate speech, business acumen, and family communication. You earn through intellectual work, trade, or writing.",
    3: "Mercury in the 3rd house is powerfully placed for communication, media, and short-distance travel. You excel in writing, publishing, and sibling relationships.",
    4: "Mercury in the 4th house brings intellectual focus to education, property matters, and domestic planning. Your home may double as a study or workspace.",
    5: "Mercury in the 5th house enhances creative intelligence, romantic communication, and connection with children through learning. You have a playful, witty mind.",
    6: "Mercury in the 6th house excels in analytical problem-solving, health diagnostics, and competitive communication. You defeat opponents through superior strategy.",
    7: "Mercury in the 7th house brings intellectual partnerships and communicative relationships. Business partnerships and marriage benefit from shared mental interests.",
    8: "Mercury in the 8th house creates research talent, occult curiosity, and diagnostic intelligence. You excel in investigation, psychology, and hidden knowledge.",
    9: "Mercury in the 9th house connects intellect to philosophy, higher education, and foreign languages. You may teach, publish, or travel for intellectual growth.",
    10: "Mercury in the 10th house drives career success through communication, business, and intellectual authority. You excel in commerce, media, or advisory roles.",
    11: "Mercury in the 11th house connects intelligence to social networks and profitable ventures. You gain through business acumen and influential friendships.",
    12: "Mercury in the 12th house turns intellect inward toward meditation, spiritual study, and foreign communication. You may excel in writing about transcendent themes.",
  },
  Jupiter: {
    1: "Jupiter in the 1st house blesses the personality with wisdom, optimism, and moral authority. You are naturally generous, philosophical, and physically expansive.",
    2: "Jupiter in the 2nd house blesses family wealth, eloquent speech, and accumulated wisdom. Financial growth comes through ethical means and generous sharing.",
    3: "Jupiter in the 3rd house expands courage, creative expression, and sibling relationships. You communicate with wisdom and inspire through writing or media.",
    4: "Jupiter in the 4th house blesses domestic happiness, property expansion, and mother's grace. Education and inner peace flourish in this placement.",
    5: "Jupiter in the 5th house is supremely auspicious for children, creativity, and spiritual practice. Intelligence expands through joyful learning and romantic wisdom.",
    6: "Jupiter in the 6th house helps overcome enemies through ethical means but may expand health issues. Service to others becomes a path of spiritual growth.",
    7: "Jupiter in the 7th house blesses partnerships with wisdom, expanding marriage and business through ethical connection. Your spouse may be wise and fortunate.",
    8: "Jupiter in the 8th house protects through crisis and expands through transformation. You may inherit wisdom, have long life, and gain through occult or insurance matters.",
    9: "Jupiter in the 9th house is the most auspicious placement — supreme dharma, fortune, and spiritual wisdom. You are blessed by teachers and higher knowledge.",
    10: "Jupiter in the 10th house brings career success through ethical leadership and wise authority. You achieve prominence through teaching, law, or spiritual guidance.",
    11: "Jupiter in the 11th house expands gains, social networks, and fulfilled aspirations. Wealth accumulates through generous connections and fortunate friendships.",
    12: "Jupiter in the 12th house is excellent for spiritual liberation, foreign connections, and charitable service. You find meaning through transcendence and giving.",
  },
  Venus: {
    1: "Venus in the 1st house blesses the personality with beauty, charm, and artistic sensibility. You attract others naturally and appreciate life's pleasures.",
    2: "Venus in the 2nd house enhances wealth through luxury goods, art, and beauty industries. Family life is comfortable, and speech is sweet and persuasive.",
    3: "Venus in the 3rd house creates artistic communication, creative siblings, and graceful self-expression. You excel in arts, music, and aesthetic media.",
    4: "Venus in the 4th house brings domestic luxury, beautiful homes, and comfortable vehicles. Emotional life is rich with pleasure and aesthetic beauty.",
    5: "Venus in the 5th house enhances romantic life, creative arts, and connection with children. Love affairs are passionate and artistically expressed.",
    6: "Venus in the 6th house may bring challenges in relationships through service dynamics. Beauty and art may be used in healing professions.",
    7: "Venus in the 7th house is perfectly placed for marriage, partnerships, and public charm. Your relationships are beautiful, harmonious, and mutually enriching.",
    8: "Venus in the 8th house creates intense romantic transformation and hidden pleasures. You attract resources through partnerships and may have mysterious allure.",
    9: "Venus in the 9th house connects love to spiritual growth and foreign beauty. You are attracted to philosophical partners and find grace through higher learning.",
    10: "Venus in the 10th house brings career success in arts, beauty, luxury, or entertainment. Your public image is attractive and professionally charming.",
    11: "Venus in the 11th house connects pleasure to social gains and fulfilled desires. You attract wealth through beauty, art, and fortunate friendships.",
    12: "Venus in the 12th house creates transcendent love, spiritual beauty, and pleasure in seclusion. Foreign romance and mystical artistic expression are highlighted.",
  },
  Saturn: {
    1: "Saturn in the 1st house creates a serious, disciplined personality that matures with age. Early life challenges build lasting character and slow but steady success.",
    2: "Saturn in the 2nd house brings financial discipline and gradual wealth accumulation. Family responsibilities are heavy but build enduring security over time.",
    3: "Saturn in the 3rd house creates cautious communication and determined courage. Sibling relationships may be strained but writing and effort bear fruit with persistence.",
    4: "Saturn in the 4th house may restrict early domestic happiness but builds lasting property and inner strength. Mother's influence involves duty and discipline.",
    5: "Saturn in the 5th house may delay children or romance but creates disciplined creativity and mature speculative judgment. Learning is structured and thorough.",
    6: "Saturn in the 6th house excels in defeating enemies through endurance and chronic health management. You overcome obstacles through sheer persistent effort.",
    7: "Saturn in the 7th house may bring delayed marriage or a mature, older partner. Relationships are structured around duty, lasting commitment, and karmic bonds.",
    8: "Saturn in the 8th house demands confrontation with mortality and karmic debts. You build strength through endurance in crisis and may have a long life.",
    9: "Saturn in the 9th house structures spiritual practice and philosophical discipline. Dharma is earned through effort, and relationship with teachers involves duty.",
    10: "Saturn in the 10th house is powerfully placed for career authority built through decades of hard work. You become an institution, earning lasting professional respect.",
    11: "Saturn in the 11th house gradually builds social networks and steady gains. Elder siblings may be responsible, and aspirations are fulfilled through patient discipline.",
    12: "Saturn in the 12th house demands spiritual discipline and may bring isolation or institutional duties. Liberation comes through confronting fears and embracing solitude.",
  },
  Rahu: {
    1: "Rahu in the 1st house amplifies personality with unconventional magnetism and ambitious worldly desire. You project a powerful, sometimes mysterious first impression.",
    2: "Rahu in the 2nd house drives unconventional wealth accumulation and unusual speech patterns. Family dynamics may be non-traditional, with sudden financial fluctuations.",
    3: "Rahu in the 3rd house amplifies communication through media, technology, and bold self-expression. You may achieve sudden success through unconventional writing or ventures.",
    4: "Rahu in the 4th house creates unusual domestic situations and desire for unconventional homes. Foreign connections to homeland and non-traditional family patterns emerge.",
    5: "Rahu in the 5th house amplifies creative ambition and unusual romantic attractions. Speculation may bring sudden gains or losses, and children may be unconventional.",
    6: "Rahu in the 6th house gives power over enemies through unconventional strategies. Health may involve unusual conditions but you overcome obstacles through innovation.",
    7: "Rahu in the 7th house attracts unconventional partnerships and possibly foreign spouses. Business dealings involve unusual dynamics and sudden relationship shifts.",
    8: "Rahu in the 8th house intensifies transformation, hidden power, and sudden upheavals. You may gain through insurance, inheritance, or occult knowledge.",
    9: "Rahu in the 9th house drives spiritual seeking through unconventional or foreign paths. You may follow unorthodox philosophies and have transformative long-distance journeys.",
    10: "Rahu in the 10th house amplifies career ambition with unconventional professional paths. Sudden rise to prominence through technology, media, or foreign connections.",
    11: "Rahu in the 11th house is excellently placed for sudden gains, influential networks, and fulfilled ambitions. You achieve through innovative social strategies.",
    12: "Rahu in the 12th house creates foreign residence, unusual spiritual experiences, and hidden expenditures. Liberation comes through surrendering worldly attachments.",
  },
  Ketu: {
    1: "Ketu in the 1st house creates a detached, spiritual personality with past-life wisdom. You may appear mysterious and are naturally drawn to transcendent pursuits.",
    2: "Ketu in the 2nd house indicates detachment from material wealth and family traditions. You may have unusual speech patterns and find values beyond material possession.",
    3: "Ketu in the 3rd house gives innate courage and past-life communication skills. You may detach from siblings and find expression through spiritual rather than worldly pursuits.",
    4: "Ketu in the 4th house creates detachment from homeland and material comfort. You may live far from birthplace and find inner peace through spiritual rather than material security.",
    5: "Ketu in the 5th house gives past-life creative and spiritual talent. Romance may feel karmically destined, and you have intuitive rather than calculated intelligence.",
    6: "Ketu in the 6th house indicates past-life mastery over enemies and disease. You have innate healing ability and may detach from competitive worldly struggle.",
    7: "Ketu in the 7th house creates detachment in partnerships and possible past-life relationship karma. Marriage may feel fated, with spiritual lessons in companionship.",
    8: "Ketu in the 8th house gives deep intuitive knowledge of transformation and occult matters. You may have natural healing ability and fearlessness around death.",
    9: "Ketu in the 9th house indicates past-life spiritual attainment and innate philosophical wisdom. You may detach from organized religion while having deep inner faith.",
    10: "Ketu in the 10th house creates detachment from career ambition and worldly status. You may find that professional success feels empty without spiritual purpose.",
    11: "Ketu in the 11th house indicates past-life social mastery and fulfilled desires. You may detach from material gains and find purpose in spiritual community.",
    12: "Ketu in the 12th house is supremely placed for spiritual liberation and moksha. You have deep past-life spiritual development and naturally gravitate toward transcendence.",
  },
};
